Added error checking for task 0

diff --git a/0x12-web_stack_debugging_2/0-iamsomeoneelse b/0x12-web_stack_debugging_2/0-iamsomeoneelse
--- a/0x12-web_stack_debugging_2/0-iamsomeoneelse
+++ b/0x12-web_stack_debugging_2/0-iamsomeoneelse
@@ -1,5 +1,11 @@
 #!/usr/bin/env bash
-# Bash script that accepts one argument
-# the script should run the whoami command under the user passed as an argument
-# make sure to try your script by passing different users
-sudo -u '$1' whoami
+
+# Check if username argument is provided
+if [ -z "$1" ]; then
+    echo "Error: Username argument is missing."
+    echo "Usage: $0 <username>"
+    exit 1
+fi
+
+# Run whoami command under the specified user
+sudo -u "$1" whoami
